config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root to: "landing_pages#index"

  get "/pages/index", to: "pages#index", as: :homepage
  get "/pages/schedule", to: "pages#schedules", as: :schedules
  get "/pages/announcements", to: "pages#announcements", as: :announcements

  get "/guidelines/school_guidelines", to: "guidelines#school_guidelines", as: :school_guidelines
  get "/guidelines/central_services_guidelines", to: "guidelines#central_services_guidelines", as: :central_services_guidelines
  get "/guidelines/auxiliary_guidelines", to: "guidelines#auxiliary_guidelines", as: :auxiliary_guidelines
  get "/guidelines/capex", to: "guidelines#capexes", as: :capexes

  resources :downloadable_forms
  resources :uploaded_forms
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/announcement.rb
class Announcement < ActiveRecord::Base
  validates :title, presence: true
  validates :announced_at, presence: true
  validates :content, presence: true
end

app/models/downloadable_form.rb
class DownloadableForm < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  validates :color, presence: true
  validates :description, presence: true
  validates :priority, presence: true, numericality: true

  has_attached_file :file
  #validates_attachment_file_name :file, :matches => [/doc\Z/, /xlsx?g\Z/, /xls\Z/, /docx\Z/]
  #validates_attachment_content_type :file, :content_type => %w(application/xml application/vnd.ms-excel application/vnd.openxmlformats-officedocument.spreadsheetml.sheet)
  do_not_validate_attachment_file_type :file

  def file_attached?
    self.file.file?
  end
end

app/models/guideline.rb
class Guideline < ActiveRecord::Base
  validates :title, presence:true, uniqueness:true
  validates :content, presence:true
  validates :posted_at, presence:true
  validates :guideline_type, presence:true

  scope :guideline_for_school, -> { where(:guideline_type => "School") }
  scope :guideline_for_central_services, -> { where(:guideline_type => "Central Services") }
  scope :guideline_for_auxiliary, -> { where(:guideline_type => "Auxiliaries") }
  scope :guideline_for_capex, -> { where(:guideline_type => "CAPEX") }
end

app/models/uploaded_form.rb
class UploadedForm < ActiveRecord::Base
  validates :uploaded_by, presence: true
  validates :unit, presence: true

  has_attached_file :file
  #validates_attachment_file_name :file, :matches => [/doc\Z/, /xlsx?g\Z/, /xls\Z/, /docx\Z/]
  #validates_attachment_content_type :file, :content_type => %w(application/xml application/vnd.ms-excel application/vnd.openxmlformats-officedocument.spreadsheetml.sheet)
  do_not_validate_attachment_file_type :file

  def file_attached?
    self.file.file?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  layout :layout_by_resource

  def layout_by_resource
    if devise_controller?
      "landing"
    else
      "application"
    end
  end


end

app/controllers/downloadable_forms_controller.rb
class DownloadableFormsController < ApplicationController

  def index
    @df = DownloadableForm.all
  end
end

app/controllers/guidelines_controller.rb
class GuidelinesController < ApplicationController 

  def school_guidelines
    @guidelines = Guideline.guideline_for_school
  end

  def central_services_guidelines 
    @guidelines = Guideline.guideline_for_central_services
  end

  def auxiliary_guidelines 
    @guidelines = Guideline.guideline_for_auxiliary
  end

  def capexes 
    @guidelines = Guideline.guideline_for_capex
  end
end

app/controllers/landing_pages_controller.rb
class LandingPagesController < ApplicationController
  layout "landing"
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def announcements
    @announcements = Announcement.all
  end
end

app/controllers/uploaded_forms_controller.rb
class UploadedFormsController < ApplicationController
  def new
    @uploaded_form = UploadedForm.new
  end

  def create
    @uploaded_form = UploadedForm.new(uploaded_form_params)

    if @uploaded_form.save
      flash[:success] = "Successfully uploaded file."
      redirect_to new_uploaded_form_path
    else
      flash[:error] = "Cannot upload file. Please check form for details."
      render "new"
    end
  end

  def uploaded_form_params
    params.require(:uploaded_form).permit!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def downloadable_forms
    return DownloadableForm.all.order(:priority)
  end
end

app/views/guidelines/auxiliary_guidelines.html.haml
:css
  .ui.segment {
    font-size: 18px!important;
  }
%section.content
  .schedules
    %h1.ui.grey.centered.header{:style => "margin-top: 40px;"} AUXILLIARY GUIDELINES
    %hr
  - @guidelines.each do |a|
    %h3.text-blue
      = a.title
      .ui.label
        = a.posted_at
    %p
      = a.content.html_safe
    %hr

app/views/guidelines/capexes.html.haml
:css
  .ui.segment {
    font-size: 18px!important;
  }
%section.content
  .schedules
    %h1.ui.grey.centered.header{:style => "margin-top: 40px;"} CAPEX GUIDELINES
    %hr
  - @guidelines.each do |a|
    %h3.text-blue
      = a.title
      .ui.label
        = a.posted_at
    %p
      = a.content.html_safe
    %hr

app/views/guidelines/central_services_guidelines.html.haml
:css
  .ui.segment {
    font-size: 18px!important;
  }
  
%section.content
  .schedules
    %h1.ui.grey.centered.header{:style => "margin-top: 40px;"} CENTRAL SERVICES GUIDELINES
    %hr
  - @guidelines.each do |a|
    %h3.text-blue
      = a.title
      .ui.label
        = a.posted_at
    %p
      = a.content.html_safe
    %hr

app/views/guidelines/school_guidelines.html.haml
:css
  .ui.segment {
    font-size: 18px!important;
  }
%section.content
  .schedules
    %h1.ui.grey.centered.header{:style => "margin-top: 40px;"} SCHOOL GUIDELINES
    %hr
  - @guidelines.each do |a|
    %h3.text-blue
      = a.title
      .ui.label
        = a.posted_at
    %p
      = a.content.html_safe
    %hr

app/views/landing_pages/index.html.haml
:css
  .container {
    font-family: "Time New Roman"!important;
  }

= render partial: "shared/header"

#accounting_image
  .white
    .container
      %h1{:style => "color: white; font-size: 50px; margin-top: 20%;"}
        Ateneo de Manila University 
        %br
        Budget Website 
        %br
        FY 2020-2021

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AteneoBudgetWebsite2017</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container-fluid">
    <%= render partial: "shared/header" %>
    <%= render partial: "shared/notification" %>
    <%= yield %>
    <%= render partial: "shared/footer" %>
  </div>
</body>
</html>

app/views/layouts/landing.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AteneoBudgetWebsite2017</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1" />
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/pages/announcements.html.haml
:css
  .ui.segment {
    font-size: 18px!important;
  }
%section.content
  .container-fluid
    .schedules
      %h1.ui.grey.centered.header{:style => "margin-top: 40px;"} ANNOUNCEMENTS
      %hr
    - @announcements.each do |a|
      %h3.text-blue
        = a.title
        .ui.label
          = a.announced_at
      %p
        = a.content.html_safe
      %hr

app/views/pages/schedules.html.haml
:css
  .ui.segment {
    font-size: 18px!important;
  }
%section.content
  .schedules
    %h1.ui.grey.centered.header{:style => "margin-top: 25px;"} 
      SCHEDULE OF MEETINGS
      %br
      UNIVERSITY BUDGET COMMITTEE
      %br
      %small
        FY 2020 - 2021
    %hr
    %table.ui.celled.table{:style => "line-height: 100px;"}
      %thead
        %tr
          %th Date
          %th Day
          %th Unit
          %th Time
      %tbody
      %tr
        %td
          .ui.blue.big.ribbon.label January 16
        %td Thursday
        %td
          * Briefing
          %br
          * VP for Basic Education (plus GS, JHS & SHS)

        %td
          9:00 am
          %br
          10:30 am

      %tr
        %td
          .ui.red.big.ribbon.label January 21
        %td Tuesday
        %td
          * VP for Loyola Schools
          (with Rizal Library and Recidence Halls)
          %br
          * VP for Professional Schools(with GSB, Law School, ASMPH, SOG, APS Lib, RBO and SBO)

        %td
          9:30 am
          %br
          1:30 pm
      %tr
        %td
          .ui.blue.big.ribbon.label January 23
        %td Thursday
        %td
          * VP for Administration &amp; HR (plus OHRMOD, ITRMO, Univ. Archives, CSMO, CFMO &amp; MPAO)
          %br
          * VP for University &amp; Global Relations
          %br
          * VP for Social Development(plus ACED, AIS &amp; Gawad Kalinga)
        %td
          9:30 am
          %br
          1:30 pm
          %br
          3:00 pm

      %tr
        %td
          .ui.red.big.ribbon.label February 4
        %td Tuesday
        %td
          * President’s Office (plus Art Gallery, OMI, OAR, IPO, UMCO, OUD, UREO, UPress, SQMO, UDPO, Arete, Univ. Athletics and ULCO)
          %br
          * General Administration
          %br
          * VP Finance &amp; Treasurer(plus Bursar, CAO and CPO)

        %td
          9:30 am
          %br
          11:00 am
          %br
          11:30 m

      %tr
        %td
          .ui.red.big.ribbon.label
            February 13
        %td Thursday
        %td
          * Review of Proposed Major Improvement and Inspection Tour
          %br
          * Review of Proposed New Positions

        %td
          9:30 am
          %br
          1:30 pm

      %tr
        %td
          .ui.red.big.ribbon.label
            February 18
        %td Thursday
        %td
          * Final Meeting
        %td 9:30 am

app/views/shared/_footer.html.haml
/ %section.content{:style => "margin-top: 100px;"}
/   %b
/     Copyright ©
/     All Rights Reserved

app/views/shared/_header.html.haml
:css
  img {
    width: 600px;
    padding-top: 10px;
  }

.ui.menu.secondary.black
  .row
    .col-md-1
    .col-md-3 
      %center
        = image_tag "logo.png", class: "ui image"
    .col-md-2
    .col-md-7
      .ui.menu
        .item
          = link_to root_path do
            %i.home.icon
            %span Home
        .item
          = link_to announcements_path do
            %i.home.icon
            %span Announcements
        .item
          = link_to schedules_path do
            %i.hospital.icon
            %span Schedules

        .ui.dropdown.item
          Guidelines
          %i.dropdown.icon
          .menu
            .item
              = link_to school_guidelines_path do
                %i.fa.fa-circle-o.text-red
                %span School Unit
            .item 
              = link_to central_services_guidelines_path do
                %i.fa.fa-circle-o.text-red
                %span Central Services
            .item
              = link_to auxiliary_guidelines_path do
                %i.fa.fa-circle-o.text-red
                %span Auxilliaries
            .item
              = link_to capexes_path do
                %i.fa.fa-circle-o.text-red
                %span CAPEX

        .item
          = link_to new_uploaded_form_path do
            %i.hospital.icon
            %span Upload Form

        .ui.dropdown.item
          Budget Forms
          %i.dropdown.icon
          .menu
            - downloadable_forms.each do |df|
              .item
                = link_to df.file.url do
                  %i.fa.fa-circle-o.text-red
                  %span{:style => "background-color: #{df.color}; padding: 6px"}
                    = df.name



:javascript
  $('.ui.dropdown').dropdown();

app/views/shared/_notification.html.erb
<% flash.each do |key, value| %>
  <% if key == "success" %>
    <script>
    $(document).on("ready page:load", function() {
      value = '<%= value %>'
      toastr.success(value);
    });
    </script>
  <% elsif key == "error" %>
    <script>
      $(document).on("ready page:load", function() {
        value = '<%= value %>'
        toastr.error(value);
      });
    </script>
  <% else %>
    <script>
      $(document).on("ready page:load", function() {
        value = '<%= value %>'
        toastr.info(value);
      });
    </script>
  <% end %>
<% end %>

<!-- DISPLAY ERRORS AS NOTIFICATIONS -->
<% if !@errors.nil? %>
  <% @errors.each do |error| %>
    <script>
      $(document).on("ready page:load", function() {
        value = '<%= error %>'
        toastr.error(value);
      });
    </script>
  <% end %>
<% end %>

app/views/shared/_sidebar.html.haml
/ :css
/   li {
/     font-size: 18px!important;
/   }

/ %aside.main-sidebar
/   %section.sidebar{style: "height: auto;"}
/     %ul.sidebar-menu
/       %li.header
/         MAIN NAVIGATION
/         %li.treeview
/           = link_to root_path do
/             %i.home.icon
/             %span Home
/         %li.treeview
/           = link_to announcements_path do
/             %i.home.icon
/             %span Announcements
/         %li.treeview
/           = link_to schedules_path do
/             %i.hospital.icon
/             %span Schedules
            
/         %li.treeview
/           = link_to root_path do
/             %i.list.icon
/             %span Guidelines
/             %i.fa.fa-angle-left.pull-right
/           %ul.treeview-menu
/             %li.treeview
/               = link_to school_guidelines_path do
/                 %i.fa.fa-circle-o.text-red
/                 %span School Unit
/             %li.treeview
/               = link_to central_services_guidelines_path do
/                 %i.fa.fa-circle-o.text-red
/                 %span Central Services
/             %li.treeview
/               = link_to auxiliary_guidelines_path do
/                 %i.fa.fa-circle-o.text-red
/                 %span Auxilliaries
/             %li.treeview
/               = link_to capexes_path do
/                 %i.fa.fa-circle-o.text-red
/                 %span CAPEX
/             %li.treeview
/               = link_to "http://budget.ateneo.net/system/downloadable_forms/files/000/000/019/original/Budget_Presentation_Template.pptx?1480147869" do
/                 %i.fa.fa-circle-o.text-red
/                 %span Budget Presentation Template

/         %li.treeview
/           = link_to root_path do
/             %i.money.icon
/             %span Budget Forms
/             %i.fa.fa-angle-left.pull-right
/           %ul.treeview-menu
/             - downloadable_forms.each do |df|
/               %li.treeview
/                 = link_to df.file.url do
/                   %i.fa.fa-circle-o.text-red
/                   %span{:style => "background-color: #{df.color}; padding: 6px"}
/                     = df.name
                  

      

/         %li.treeview
/           = link_to new_uploaded_form_path do
/             %i.upload.icon
/             %span Upload Forms
      
  
      
      
        



   

app/views/uploaded_forms/new.html.haml
%section.content
  = render partial: "shared/notification"

  %h1.ui.grey.centered.header{:style => "margin-top: 25px;"} UPLOAD FORMS
  %center You may upload completed budget forms here. Please specify your name and select the corresponding unit from the list.
  %hr
  = simple_form_for @uploaded_form, defaults: { wrapper_html: { class: 'form-group' }, input_html: { class: 'form-control' } }, html: { multipart: true, novalidate: true } do |f|
    .ui.segment
      .ui.form
        .field
          = f.input :uploaded_by
        .field
          = f.input :unit, as: :select, collection: ["SCHOOL", "AUXILIARY", "SERVICE", "OTHER"]
        .field
          = f.input :file, as: :file
        .field
          = f.submit "Submit", class: "btn btn-primary"